#!/usr/bin/env tsx
import path from 'path';
import fs from 'fs';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..');
const APP_DIR = path.join(PROJECT_ROOT, 'app');
const OUTPUT_DIR = path.join(APP_DIR, 'generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'pages.ts');

type RouteMeta = {
  title: string;
  description: string;
  image?: string;
};

type PageInfo = {
  id: string;
  title: string;
  description: string;
  image: string | null;
  enabled: boolean;
  path: string;
};

type CategoryInfo = {
  id: string;
  title: string;
  description: string;
  order: number;
  pages: PageInfo[];
};

type RouteManifest = {
  categories: CategoryInfo[];
};

function formatPath(categoryId: string, pageId: string): string {
  return `/${categoryId}/${pageId}`;
}

async function importWithBust(filePath: string) {
  const url = new URL(`file://${filePath}`);
  url.searchParams.set('t', Date.now().toString());
  return import(url.href);
}

async function main() {
  const pagesModulePath = path.join(APP_DIR, 'pages.ts');
  const pagesModule = await importWithBust(pagesModulePath);

  const categories: typeof pagesModule.categories = pagesModule.categories;

  const manifest: RouteManifest = { categories: [] as CategoryInfo[] };

  for (const category of categories) {
    const pages: PageInfo[] = [];

    for (const pageDef of category.pages) {
      const metaFilePath = path.join(
        APP_DIR,
        'routes',
        category.id,
        pageDef.id,
        'meta.ts',
      );

      if (!fs.existsSync(metaFilePath)) {
        console.warn(
          `⚠️  Missing meta file for ${category.id}/${pageDef.id}, skipping.`,
        );
        continue;
      }

      const metaModule = await importWithBust(metaFilePath);
      const meta = metaModule.routeMeta as RouteMeta;

      pages.push({
        id: pageDef.id,
        title: meta.title,
        description: meta.description,
        image: meta.image ?? null,
        enabled: pageDef.enabled,
        path: formatPath(category.id, pageDef.id),
      });
    }

    manifest.categories.push({
      id: category.id,
      title: category.title,
      description: category.description,
      order: category.order,
      pages,
    });
  }

  const output = `// Auto-generated by scripts/generate-pages.ts — do not edit manually
export const routeManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

  const totalPages = manifest.categories.reduce(
    (sum, c) => sum + c.pages.length,
    0,
  );
  const enabledPages = manifest.categories.reduce(
    (sum, c) => sum + c.pages.filter((p: PageInfo) => p.enabled).length,
    0,
  );

  console.log(
    `✅ Generated manifest: ${manifest.categories.length} categories, ${totalPages} pages (${enabledPages} enabled)`,
  );
}

const isWatch = process.argv.includes('--watch');

if (isWatch) {
  const routesDir = path.join(APP_DIR, 'routes');
  const pagesFile = path.join(APP_DIR, 'pages.ts');

  await main();

  console.log('👀 Watching for changes...');
  fs.watch(routesDir, { recursive: true }, (event, filename) => {
    if (filename?.endsWith('.ts') || filename?.endsWith('.tsx')) {
      console.log(`🔄 Change detected: ${filename}`);
      main().catch(console.error);
    }
  });
  fs.watch(pagesFile, () => {
    console.log('🔄 pages.ts changed');
    main().catch(console.error);
  });

  // Keep alive
  await new Promise(() => {});
} else {
  await main().catch(console.error);
}
